/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import CONTROLLER.OPrincipal;

/**
 *
 * @author juanm
 */
public class GUI_Principal extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Principal
     */
    
    OPrincipal oyentePrincipal;
    public GUI_Principal() {
        
        initComponents();
        oyentePrincipal = new  OPrincipal(this,BTMembresias,BTProductos,BTEventos, BTRutinas,BTIIcono); //this para mandar toda la gui
        BTMembresias.addActionListener(oyentePrincipal);
        BTProductos.addActionListener(oyentePrincipal);
        BTEventos.addActionListener(oyentePrincipal);
        BTRutinas.addActionListener(oyentePrincipal);
        BTIIcono.addActionListener(oyentePrincipal);
        setLocationRelativeTo(null); //centrar el frame
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        BTMembresias = new javax.swing.JButton();
        BTIIcono = new javax.swing.JButton();
        BTProductos = new javax.swing.JButton();
        BTEventos = new javax.swing.JButton();
        BTRutinas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BLACK PANTHERS GYM");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setText("Buscar producto o evento");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, 190, 30));

        BTMembresias.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        BTMembresias.setText("Membresías");
        BTMembresias.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BTMembresias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTMembresias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTMembresiasActionPerformed(evt);
            }
        });
        jPanel2.add(BTMembresias, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 110, 30));

        BTIIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono.png"))); // NOI18N
        BTIIcono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BTIIcono.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTIIcono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTIIconoActionPerformed(evt);
            }
        });
        jPanel2.add(BTIIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 30, 50, 40));

        BTProductos.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        BTProductos.setText("Productos");
        BTProductos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BTProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTProductosActionPerformed(evt);
            }
        });
        jPanel2.add(BTProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 110, 30));

        BTEventos.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        BTEventos.setText("Eventos");
        BTEventos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BTEventos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTEventos.setFocusPainted(false);
        BTEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTEventosActionPerformed(evt);
            }
        });
        jPanel2.add(BTEventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 110, 30));

        BTRutinas.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        BTRutinas.setText("Rutinas");
        BTRutinas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(BTRutinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 110, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gym.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 750));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void BTMembresiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTMembresiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTMembresiasActionPerformed

    private void BTEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTEventosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTEventosActionPerformed

    private void BTProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTProductosActionPerformed

    private void BTIIconoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTIIconoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTIIconoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_AgregarProducto_G.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_AgregarProducto_G.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_AgregarProducto_G.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_AgregarProducto_G.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GUI_Principal().setVisible(true);
        });

//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTEventos;
    private javax.swing.JButton BTIIcono;
    private javax.swing.JButton BTMembresias;
    private javax.swing.JButton BTProductos;
    private javax.swing.JButton BTRutinas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
